[package]
name = "fsm"
version = "0.1.0"
authors = ["Rudi Benkovic <rudi.benkovic@gmail.com>"]

[features]
default = ["std"]
std = []
core_collections = []

[workspace]
members = ["fsm_codegen", "fsm_tests"]