[package]
name = "fsm_tests"
version = "0.5.0"
authors = ["Rudi Benkovic <rudi.benkovic@gmail.com>", "Maher Sallam <msallam@rocsys.com>"]
edition = "2018"

[dependencies]
async-trait = "0.1.42"
tokio = { version = "1.2.0", features = ["full"] }


[dev-dependencies]
assert_matches = "1.5.0"
